# [".vim/autoload/plug.vim"]
#     type = "file"
#     url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
#     refreshPeriod = "168h"
# [".vim/colors/one.vim"]
#     type = "file"
#     url = "https://raw.githubusercontent.com/rakr/vim-one/master/colors/one.vim"
#     refreshPeriod = "168h"